
import java.awt.ComponentOrientation;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author arka5
 */
public class SettingsView extends javax.swing.JPanel {

    /**
     * Creates new form SettingsView
     */
    JDialog parentContainer;
    public SettingsView(JDialog parentContainer) {
        initComponents(); 
        this.parentContainer = parentContainer;
        edPlayer1.setComponentOrientation(ComponentOrientation.LEFT_TO_RIGHT);
        edPlayer2.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        edPlayer1 = new javax.swing.JTextField();
        lblPlayer2 = new javax.swing.JLabel();
        edPlayer2 = new javax.swing.JTextField();
        lblPlayer1 = new javax.swing.JLabel();
        lblHeadline = new javax.swing.JLabel();
        btnOK = new javax.swing.JButton();

        edPlayer1.setText("Player 1");
        edPlayer1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                edPlayer1FocusGained(evt);
            }
        });

        lblPlayer2.setText("Player 2");

        edPlayer2.setText("Player 2");
        edPlayer2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                edPlayer2FocusGained(evt);
            }
        });

        lblPlayer1.setText("Player 1");
        lblPlayer1.setName(""); // NOI18N

        lblHeadline.setText("Please choose a nickname for each player.");

        btnOK.setText("Confirm");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHeadline)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnOK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(edPlayer1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                                .addComponent(edPlayer2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPlayer1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblPlayer2)
                                .addGap(5, 5, 5)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblHeadline)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPlayer1)
                    .addComponent(lblPlayer2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edPlayer2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edPlayer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnOK)
                .addContainerGap(16, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void edPlayer1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edPlayer1FocusGained
        edPlayer1.setCaretPosition(0);
        edPlayer1.selectAll();              
    }//GEN-LAST:event_edPlayer1FocusGained

    private void edPlayer2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edPlayer2FocusGained
        edPlayer2.setCaretPosition(0);
        edPlayer2.selectAll();       
    }//GEN-LAST:event_edPlayer2FocusGained

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        if (CheckFields())
            parentContainer.setVisible(false);
        else
            JOptionPane.showMessageDialog(this,"Invalid Input");
    }//GEN-LAST:event_btnOKActionPerformed
    
    
    private boolean CheckFields()
    {
        if (edPlayer1.getText() == null || edPlayer1.getText().trim().isEmpty())
            return false;
        if (edPlayer2.getText() == null || edPlayer2.getText().trim().isEmpty())
            return false;
        return true;        
    }
    
    public String getNamePlayer1()
    {
        String name = "Player 1";
        if (CheckFields())
            name = edPlayer1.getText();
        return name;
    }

    public String getNamePlayer2()
    {
        String name =  "Player 2";        
        if (CheckFields())
            name = edPlayer2.getText();
        return name;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOK;
    private javax.swing.JTextField edPlayer1;
    private javax.swing.JTextField edPlayer2;
    private javax.swing.JLabel lblHeadline;
    private javax.swing.JLabel lblPlayer1;
    private javax.swing.JLabel lblPlayer2;
    // End of variables declaration//GEN-END:variables
}
